version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ShieldQuery
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: 12345678!
      POSTGRES_DB: shield_query
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
